import { z } from 'zod';

export const metaCloudConfigSchema = z.object({
  wabaId: z.string().min(1),
  phoneNumberId: z.string().min(1),
  accessToken: z.string().min(1),           // encrypted ciphertext (enc:...)
  appSecret: z.string().min(1),             // encrypted ciphertext (enc:...)
  webhookVerifyToken: z.string().min(8),    // generated by us, plaintext
  webhookSubscribed: z.boolean().default(false),
});

export type MetaCloudConfig = z.infer<typeof metaCloudConfigSchema>;
