import { z } from 'zod';

export const metaCloudConfigSchema = z.object({
  wabaId: z.string().min(1),
  phoneNumberId: z.string().min(1),
  accessToken: z.string().min(1),           // encrypted ciphertext (enc:...)
  appSecret: z.string().min(1),             // encrypted ciphertext (enc:...)
  webhookVerifyToken: z.string().min(8),    // generated by us, plaintext
  webhookSubscribed: z.boolean().default(false),
  // App ID da Meta (não é segredo) — necessário pro Resumable Upload da imagem
  // de header de templates HSM. Opcional: instâncias antigas podem não ter.
  appId: z.string().min(1).optional(),
});

export type MetaCloudConfig = z.infer<typeof metaCloudConfigSchema>;
